name: Python Linters

on: [push, pull_request]

jobs:

  ubuntu-lint:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements_linux.txt
        pip install pytest-pylint pytest-flake8
    - name: Analysing the code with pylint
      run: |
        source check_pylint.sh
    - name: Analysing the code with flake8
      run: |
        flake8 --max-line-length=200 \
               --statistics \
               --count \
               --per-file-ignores="__init__.py:F401"

  windows-lint:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements_windows.txt
        pip3 install pytest-pylint pytest-flake8
    - name: Analysing the code with pylint
      shell: bash
      run: |
        source check_pylint.sh
    - name: Analysing the code with flake8
      run: |
        flake8 --max-line-length=200 `
               --statistics `
               --count `
               --per-file-ignores="__init__.py:F401"
