name: Unit test

on:
  push:
    branches:
      - develop
      - main
      - master
  pull_request:

jobs:
  unit_test:
    strategy:
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Setting up Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements_ci.txt
          python -m pip install openvino-dev[tensorflow2]==2022.3.0

      - name: Run unit test
        run: python -m pytest --import-mode=append src/benchmark/tests/
